### PR TITLE
Adding Support for Debian family systems

### PR DESCRIPTION
**Pull request by alathers**
Support for SSSD deployment and configuration on Debian and Ubuntu systems.  This has been successfully tested and deployed to Ubuntu12, Ubuntu14, Ubuntu 16, Debian7 and Debian8 systems.  Inclusion of an sssd cache purging mechanism was in-line with this OS support add to address an instability in older versions of the SSSD daemon that cause slow downs/crashing of the deamon when cache size is large.

References:
https://fedorahosted.org/sssd/ticket/1729
https://fedorahosted.org/sssd/ticket/1806
https://fedorahosted.org/sssd/ticket/1893
https://bugzilla.redhat.com/show_bug.cgi?id=888739

Some notes related to sssd cache management:   
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Deployment_Guide/sssd-cache.html

$     bundle exec rake test
....

Deprecation Warnings:

`RSpec::Core::ExampleGroup.display_name` is deprecated. Use `RSpec::Core::ExampleGroup.description` instead. Called from .bundle/ruby/2.0.0/rspec-puppet-389f99ef6665/lib/rspec-puppet/support.rb:18:in `load_catalogue'.

If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
1 deprecation warning total

Finished in 1.92 seconds
43 examples, 0 failures

### CODE REVIEW

**Comment by alathers** [comment]
I'd run the job tests manually prior to the PR.  Looks like the CI job has some version issues causing failures, but generally these should I think, pass.  I'll investigate

**Comment by walkamongus** [comment]
Thanks! I'll take a look as well.

**Comment by walkamongus** [comment]
it looks like some gem dependencies updated -- I've seem something very similar on another module recently. I'll take a look and fix.

Thanks for investigating!

**Comment by walkamongus** [comment]
Hi @alathers -- I just pushed some updates that fix tests as well as test against updated version of Ruby and Puppet.  Can you rebase onto master?

**Comment by alathers** [comment]
Yep, I just gave it a go.  From what I could tell the rebase between your latest updates, and my branch were some adjustments to formatting in spec/classes/sssd.rb, and some content in Gemfile.lock.  I'll keep an eye on the build to make sure I didn't mess anything up

**Comment by alathers** [comment]
Hm, it looks like the ::operatingsystem fact isn't available to the build job?

**Comment by walkamongus** [comment]
Hi @alathers I'm going to switch the module over to using rspec-puppet-facts.

Can we migrate that `::operatingsystem` check from config.pp to a flag in params.pp? IT's usually a good idea to contain all the operating system support stuff contained in params.

Thanks!

**Comment by alathers** [comment]
Will do.  Sorry, Holiday family chaos.  I hope to take a whack at this within the next 2-3 days max.  Thanx!

**Comment by walkamongus** [comment]
@alathers  -- no problem at all! You should rebase as well as I recently pushed some changes fixing up spec files as well as adding rspec-puppet-facts. Adding Debian support to `metadata.json` should automatically populate the Debian-specific facts for the tests when it loops through all the supported operating systems.

**Comment by walkamongus** [comment]
Hi @alathers -- sorry if I wasn't very clear about moving the sssd control resources.

You can keep the resources themselves in `config.pp`. What you'd want to do is create a variable in `params.pp` -- something like `pam_mkhomedir_method` -- and then set it's value to 'file' or 'authconfig'.

Then in `config.pp` you could check the value of `pam_mkhomedir_method` and include the right resource depending on its value. This way only key/values live in params.pp, so when the module moves to the Puppet 4 lookup utility, these keys can be forklifted into the module's Hiera data and `params.pp` will go away.

I also noticed that you added `authconfig` commands for enabling sssd on the redhat osfamily. I think I had originally avoiding that to keep `authconfig` from stomping on the sssd config file. Do you know if `authconfig` will preserve the config file?

Thanks!

**Comment by seaninspace** [comment]
@walkamongus - authconfig wont touch the contents of /etc/sssd/sssd.conf. From the man page:

 The --enablesssd and --enablesssdauth options force adding SSSD to /etc/nsswitch.conf and /etc/pam.d/system-auth, but they do not set up the  domain
       in  the  SSSD configuration files. The SSSD configuration has to be set up manually.

**Comment by walkamongus** [comment]
ok sounds good -- thanks!

**Comment by alathers** [comment]
Alright, I finally had cycles to sort it all out.  Redid the pattern for the config/params bit.  adjusted the specs to pass, and adjusted the Gemfile to compensate for a gem dep fail in travis.  I set up travis on my own repo too and all the tests look to pass.

**Comment by walkamongus** [comment]
merged!

**Pull request merged**
